### PR TITLE
Add pathNames and queryKey

### PR DESCRIPTION
**Pull request by xiCO2k**
### pathNames will work like this:

parseUri('/foo/bar');
image

### queryKey will work like this:

parseUri('?foo=bar&foo2=bar2');
image

Super useful helpers.

Thanks.

### CODE REVIEW

**Comment by xiCO2k** [comment]
let me know if everything is good thanks

**Comment by xiCO2k** [comment]
Hey @get any luck? Thanks

**Comment by xiCO2k** [comment]
Hey @get can you take a look on the pull request? Thanks

**Comment by xiCO2k** [comment]
Hey @get can you some time to take a look on my pull request? Thanks

**Comment by xiCO2k** [comment]
Hey @galkn can you take a look on my pull request?

**Comment by galkn** [comment]
Hi @xiCO2k apologies for the delay, merged.

**Comment by xiCO2k** [comment]
No problem at all, It's possible also to publish to npm?

Thanks Man

**Comment by xiCO2k** [comment]
Many thanks, just saw

**Pull request merged**
